import 'package:flutter/material.dart';

import 'communitys/models.dart';

class Constants {
  //Primary color
  static var primaryColor = const Color(0xFF8C52FF);
  static var textColor = const Color(0xFF6B4EFF);
  static TextStyle titleTextStyle = const TextStyle(
    fontSize: 20,
    fontWeight: FontWeight.w700,
    letterSpacing: 0.3,
  );
  static const hobbyImageMap = <String, AssetImage>{
    "낭독 봉사": AssetImage("assets/hobby/낭독 봉사.jpg"),
    "가죽 공예": AssetImage("assets/hobby/가죽 공예.jpg"),
    "골프": AssetImage("assets/hobby/골프.jpg"),
    "나무 심기 봉사": AssetImage("assets/hobby/나무 심기 봉사.jpg"),
    "낚시": AssetImage("assets/hobby/낚시.jpg"),
    "등산": AssetImage("assets/hobby/등산.jpg"),
    "뜨개질": AssetImage("assets/hobby/뜨개질.jpg"),
    "러닝": AssetImage("assets/hobby/러닝.jpg"),
    "레고 조립": AssetImage("assets/hobby/레고 조립.jpg"),
    "마술": AssetImage("assets/hobby/마술.jpg"),
    "미술": AssetImage("assets/hobby/미술.jpg"),
    "바베큐": AssetImage("assets/hobby/바베큐.jpg"),
    "반려식물": AssetImage("assets/hobby/반려식물.jpg"),
    "배드민턴": AssetImage("assets/hobby/배드민턴.jpg"),
    "베이비박스 봉사": AssetImage("assets/hobby/베이비박스 봉사.jpg"),
    "베이킹": AssetImage("assets/hobby/베이킹.jpg"),
    "보드게임": AssetImage("assets/hobby/보드게임.jpg"),
    "볼링": AssetImage("assets/hobby/볼링.jpg"),
    "비디오게임": AssetImage("assets/hobby/비디오게임.jpg"),
    "사진": AssetImage("assets/hobby/사진.jpg"),
    "산책": AssetImage("assets/hobby/산책.jpg"),
    "서핑": AssetImage("assets/hobby/서핑.jpg"),
    "스케이트 보드": AssetImage("assets/hobby/스케이트 보드.jpg"),
    "스키": AssetImage("assets/hobby/스키.jpg"),
    "여행": AssetImage("assets/hobby/여행.jpg"),
    "연극": AssetImage("assets/hobby/연극.jpg"),
    "영화": AssetImage("assets/hobby/영화.jpg"),
    "유기견 봉사": AssetImage("assets/hobby/유기견 봉사.jpg"),
    "음악": AssetImage("assets/hobby/음악.jpg"),
    "인테리어": AssetImage("assets/hobby/인테리어.jpg"),
    "자전거": AssetImage("assets/hobby/자전거.jpg"),
    "전시회": AssetImage("assets/hobby/전시회.jpg"),
    "천체관측": AssetImage("assets/hobby/천체관측.jpg"),
    "캘리그라피": AssetImage("assets/hobby/캘리그라피.jpg"),
    "캠핑": AssetImage("assets/hobby/캠핑.jpg"),
    "코딩": AssetImage("assets/hobby/코딩.jpg"),
    "크로스핏": AssetImage("assets/hobby/크로스핏.jpg"),
    "클라이밍": AssetImage("assets/hobby/클라이밍.jpg"),
    "타로": AssetImage("assets/hobby/타로.jpg"),
    "테니스": AssetImage("assets/hobby/테니스.jpg"),
    "풋살": AssetImage("assets/hobby/풋살.jpg"),
    "필라테스": AssetImage("assets/hobby/필라테스.jpg"),
    "홈브루": AssetImage("assets/hobby/홈브루.jpg"),
    "홈카페": AssetImage("assets/hobby/홈카페.jpg"),
  };

  static Map<int, Community> communities = {
    1: Community(communityId: 1, communityName: "낭독 봉사"),
    2: Community(communityId: 2, communityName: "가죽 공예"),
    3: Community(communityId: 3, communityName: "골프"),
    4: Community(communityId: 4, communityName: "나무 심기 봉사"),
    5: Community(communityId: 5, communityName: "낚시"),
    6: Community(communityId: 6, communityName: "등산"),
    7: Community(communityId: 7, communityName: "뜨개질"),
    8: Community(communityId: 8, communityName: "러닝"),
    9: Community(communityId: 9, communityName: "레고 조립"),
    10: Community(communityId: 10, communityName: "마술"),
    11: Community(communityId: 11, communityName: "미술"),
    12: Community(communityId: 12, communityName: "바베큐"),
    13: Community(communityId: 13, communityName: "반려식물"),
    14: Community(communityId: 14, communityName: "배드민턴"),
    15: Community(communityId: 15, communityName: "베이킹"),
    16: Community(communityId: 16, communityName: "보드게임"),
    17: Community(communityId: 17, communityName: "볼링"),
    18: Community(communityId: 18, communityName: "비디오게임"),
    19: Community(communityId: 19, communityName: "사진"),
    20: Community(communityId: 20, communityName: "산책"),
    21: Community(communityId: 21, communityName: "서핑"),
    22: Community(communityId: 22, communityName: "스케이트 보드"),
    23: Community(communityId: 23, communityName: "스키"),
    24: Community(communityId: 24, communityName: "여행"),
    25: Community(communityId: 25, communityName: "연극"),
    26: Community(communityId: 26, communityName: "영화"),
    27: Community(communityId: 27, communityName: "유기견 봉사"),
    28: Community(communityId: 28, communityName: "음악"),
    29: Community(communityId: 29, communityName: "인테리어"),
    30: Community(communityId: 30, communityName: "자전거"),
    31: Community(communityId: 31, communityName: "전시회"),
    32: Community(communityId: 32, communityName: "천체관측"),
    33: Community(communityId: 33, communityName: "캘리그라피"),
    34: Community(communityId: 34, communityName: "캠핑"),
    35: Community(communityId: 35, communityName: "코딩"),
    36: Community(communityId: 36, communityName: "크로스핏"),
    37: Community(communityId: 37, communityName: "클라이밍"),
    38: Community(communityId: 38, communityName: "타로"),
    39: Community(communityId: 39, communityName: "테니스"),
    40: Community(communityId: 40, communityName: "풋살"),
    41: Community(communityId: 41, communityName: "필라테스"),
    42: Community(communityId: 42, communityName: "홈브루"),
    43: Community(communityId: 43, communityName: "홈카페"),
  };

  static List<Community> get communitiesList {
    return communities.values.toList();
  }
}
